{% set name = "queuelib" %}
{% set version = "1.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/queuelib-{{ version }}.tar.gz
  sha256: 4b207267f2642a8699a1f806045c56eb7ad1a85a10c0e249884580d139c2fcd2

build:
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - queuelib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scrapy/queuelib
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Collection of persistent (disk-based) queues
  description: |
    Queuelib goals are speed and simplicity.
  doc_url: https://pypi.python.org/pypi/queuelib
  dev_url: https://github.com/scrapy/queuelib
